branch diff

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -1,68 +1,34 @@
----
-format_version: '11'
+format_version: "11"
 default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
 project_type: ios
 workflows:
-  App2:
-    description: |
-      The workflow  the tests. The *retry_on_failure* test repetition mode is enabled.
-    steps:
-    - activate-ssh-key@4: {}
-    - git-clone@7: {}
-    - cache-pull@2: {}
-    - recreate-user-schemes@1:
-        inputs:
-        - project_path: "$BITRISE_PROJECT_PATH"
-    - xcode-test@4:
-        inputs:
-        - project_path: "$BITRISE_PROJECT_PATH"
-        - scheme: "$BITRISE_SCHEME"
-        - test_repetition_mode: retry_on_failure
-    - cache-push@2: {}
-    - deploy-to-bitrise-io@2: {}
-  App1:
-    description: |
-      The workflow  the tests.
-    steps:
-    - activate-ssh-key@4: {}
-    - git-clone@7: {}
-    - cache-pull@2: {}
-    - recreate-user-schemes@1:
-        inputs:
-        - project_path: "$BITRISE_PROJECT_PATH"
-    - xcode-test@4:
-        inputs:
-        - project_path: "$BITRISE_PROJECT_PATH"
-        - scheme: "$BITRISE_SCHEME"
-        - test_repetition_mode: retry_on_failure
-    - cache-push@2: {}
-    - deploy-to-bitrise-io@2: {}
   General:
     description: |
       The workflow to run when code not related to app has changed in PR and / or main
     steps:
     - activate-ssh-key@4: {}
     - git-clone@7: {}
-    - script@1.1:
-        title: Compress Derived Data
-        is_always_run: true
+    - script@1:
         inputs:
-        - content: |
-            echo "Just checking this is running General workflow"
-    - cache-pull@2: {}
-    - cache-push@2: {}
+        - content: |-
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -e
+            # make pipelines' return status equal the last command to exit with a non-zero status, or zero if all commands exit successfully
+            set -o pipefail
+            # debug log
+            set -x
+
+            # write your script here
+            echo "Hello World!"
+            echo "Destination Branch: $BITRISEIO_GIT_BRANCH_DEST"
+            echo "Branch being merged: $BITRISE_GIT_BRANCH"
+            echo "The git diff: "
+            git diff $BITRISEIO_GIT_BRANCH_DEST..$BITRISE_GIT_BRANCH
     - deploy-to-bitrise-io@2: {}
 trigger_map:
-- push_branch: app2-*
-  workflow: App2
-- push_branch: app1-*
-  workflow: App1
 - push_branch: general-*
   workflow: General
-- pull_request_source_branch: app1-*
-  workflow: App1
-- pull_request_source_branch: app2-*
-  workflow: App2
 - pull_request_source_branch: general-*
   workflow: General
 meta:
